name: grow_extensions
description: Fancy, yet basically useless extensions for dart language that we use across our multiple projects.
version: 0.1.2
repository: https://github.com/Code-Growers/grow_hooks
issue_tracker: https://github.com/Code-Growers/grow_hooks/issues
homepage: https://codegrowers.tech

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  index_generator: 3.4.1

flutter:
  generate: true
