name: grow_extensions
description: Fancy, yet basically useless extensions for dart language that we use across our multiple projects.
version: 0.2.1
repository: https://github.com/Code-Growers/grow_hooks
issue_tracker: https://github.com/Code-Growers/grow_hooks/issues
homepage: https://codegrowers.tech

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  index_generator: 4.1.0

flutter:
  generate: true
